version: '3'

services:
    oro:
        image: alpine
        depends_on: 
            - nginx
            - php
            - db-pg
        networks:
            - shop
            
    # PostgresSQL instead of MySQL
    db-pg:
        image: postgres:9
        # command: '' # workaround to override the default mysql db command in docker-compose.yml
        environment:
            POSTGRES_USER: ${MYSQL_USER}
            POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
            POSTGRES_DB: ${MYSQL_DATABASE}
            PGDATA: /tmp
        volumes:
            - postgresData:/var/lib/postgresql/data
        networks:
            - shop

    pga:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "user@example.com"
            PGADMIN_DEFAULT_PASSWORD: "password"
        ports:
            - "8082:80"
        depends_on:
            - db
        networks:
            - shop

volumes:
    postgresData: