version: '3'

services:
  oro:
    image: alpine
    depends_on:
      - nginx
      - php
      - db
    networks:
      - teachers
  # PostgresSQL instead of MySQL
  rediscache:
    image: redis
    networks:
      - teachers
  redissess:
    image: redis
    networks:
      - teachers
  db:
    image: postgres:9.6.20
    # command: '' # workaround to override the default mysql db command in docker-compose.yml
    environment:
      POSTGRES_DB: ${MYSQL_DATABASE}
      POSTGRES_USER: ${MYSQL_USER}
      POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
      PGDATA: /tmp
    ports:
      - 15432:5432
    networks:
      - teachers
#  pga:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "user@example.com"
#      PGADMIN_DEFAULT_PASSWORD: "password"
#    ports:
#      - "8082:80"
#    depends_on:
#      - db
#    networks:
#      - teachers
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
#    command: tar -xzf vendor.tar.gz
    tmpfs:
      - /var/www/shop/vendor:exec,mode=777,size=2G,uid=1000,gid=33
      - /var/www/shop/var/cache:mode=777,size=2G,uid=1000,gid=33
    volumes:
      - sync-public:/var/www/shop/public
      - sync-src:/var/www/shop/src
      - sync-config:/var/www/shop/config
      - sync-templates:/var/www/shop/templates
      - sync-bin:/var/www/shop/bin
      - sync-var-logs:/var/www/shop/var/logs
    links:
      - db
    depends_on:
      - db
    networks:
      - teachers
  php-ws:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
#    command: tar -xzf vendor.tar.gz
    tmpfs:
      - /var/www/shop/vendor:exec,mode=777,size=2G,uid=1000,gid=33
      - /var/www/shop/var/cache:mode=777,size=2G,uid=1000,gid=33
    volumes:
      - sync-public:/var/www/shop/public
      - sync-src:/var/www/shop/src
      - sync-config:/var/www/shop/config
      - sync-templates:/var/www/shop/templates
      - sync-bin:/var/www/shop/bin
      - sync-var-logs:/var/www/shop/var/logs
    links:
      - db
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - teachers
    entrypoint: [ '/usr/local/bin/run-websocket' ]
  # PHP Message Consumer
  php-mq:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    tmpfs:
      - /var/www/shop/vendor:exec,mode=777,size=2G,uid=1000,gid=33
      - /var/www/shop/var/cache:mode=777,size=2G,uid=1000,gid=33
    volumes:
      - sync-src:/var/www/shop/src
      - sync-config:/var/www/shop/config
      - sync-templates:/var/www/shop/templates
      - sync-bin:/var/www/shop/bin
      - sync-var-logs:/var/www/shop/var/logs
    links:
      - db
    depends_on:
      - db
      - php
    networks:
      - teachers
    entrypoint: ['/usr/local/bin/run-message-consumer']
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - sync-public:/var/www/shop/public
      - sync-src:/var/www/shop/src
      - sync-config:/var/www/shop/config
      - sync-templates:/var/www/shop/templates
      - sync-bin:/var/www/shop/bin
    ports:
      - 1080:80
    depends_on:
      - php
    networks:
      - teachers
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 11025:1025 # smtp server
      - 18025:8025 # web ui
    networks:
      - teachers
volumes:
  sync-src:
    driver_opts:
      type: 'tmpfs'
      o: 'bind'
      device: ${SHOP_HOST_DIR_SRC}
  sync-config:
    driver_opts:
      type: 'tmpfs'
      o: 'bind'
      device: ${SHOP_HOST_DIR_CONFIG}
  sync-templates:
    driver_opts:
      type: 'tmpfs'
      o: 'bind'
      device: ${SHOP_HOST_DIR_TEMPLATES}
  sync-bin:
    driver_opts:
      type: 'tmpfs'
      o: 'bind'
      device: ${SHOP_HOST_DIR_BIN}
  sync-public:
    driver_opts:
      type: 'tmpfs'
      o: 'bind'
      device: ${SHOP_HOST_DIR_PUBLIC}
  sync-var-logs:
    driver_opts:
      type: 'tmpfs'
      o: 'bind'
      device: ${SHOP_HOST_DIR_VAR_LOGS}
networks:
  teachers:
