#!/usr/bin/env bash

bin/stop-mq

docker-compose exec --env PGPASSWORD=password -T php psql -U CRYpcypcOzMIk --host=db zmikliofi -c 'create database temp1;'
docker-compose exec --env PGPASSWORD=password -T php psql -U CRYpcypcOzMIk --host=db temp1 -c 'drop database zmikliofi;'
docker-compose exec --env PGPASSWORD=password -T php psql -U CRYpcypcOzMIk --host=db temp1 -c 'create database zmikliofi;'
docker-compose exec --env PGPASSWORD=password -T php psql -U CRYpcypcOzMIk --host=db zmikliofi -c 'drop database temp1;'
docker-compose exec --env PGPASSWORD=password -T php psql -U CRYpcypcOzMIk --host=db zmikliofi -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
docker-compose exec --env PGPASSWORD=password -T php psql -U CRYpcypcOzMIk --host=db zmikliofi -c 'ALTER SEQUENCE teachers_assignment_id_seq START 1000;'

docker-compose exec -T php bash bin/install.sh

bin/start
