---
composer_version: '1.10.16'

php_webserver_daemon: nginx
php_enable_php_fpm: true

php_packages:
  - php7.3
  - php7.3-apcu
  - php7.3-bz2
  - php7.3-bcmath
  - php7.3-common
  - php7.3-cli
  - php7.3-curl
  - php7.3-gd
  - php7.3-gmp
  - php7.3-fpm
  - php7.3-intl
  - php7.3-imap
  - php7.3-mbstring
  - php7.3-mcrypt
  - php7.3-opcache
  - php7.3-pdo
  - php7.3-pgsql
  - php7.3-redis
  - php7.3-soap
  - php7.3-tidy
  - php7.3-xml
  - php7.3-zip

php_default_version_debian: "7.3"
